
import { z } from "zod";

import {
  AuthMessage, PingMessage, ConfigReloadMessage,
  SendMessageMsg, CountUnreadMessage, ReadMessagesMessage, ListAccountsMessage, ArchiveMessagesMessage,
  HandoffTaskMessage, ReauthorizeDelegationMessage, HandoffAcceptMessage, SuggestAssigneeMessage,
  UpdateTaskStatusMessage, ReportProgressMessage, AdaptiveSlaCheckMessage,
  GetTrustMessage, ReinstateAgentMessage, CheckCircuitBreakerMessage,
  PrepareWorktreeMessage, GetWorkspaceStatusMessage, CleanupWorkspaceMessage,
  CouncilAnalyzeMessage, CouncilVerifyMessage, CouncilDiscussionMessage, CouncilHistoryMessage,
} from "./message-schemas";

import {
  SearchKnowledgeMessage, IndexNoteMessage,
  ShareSessionMessage, JoinSessionMessage, SessionBroadcastMessage, SessionStatusMessage,
  SessionHistoryMessage, LeaveSessionMessage, SessionPingMessage, NameSessionMessage,
  ListSessionsMessage, SearchSessionsMessage,
  WorkflowTriggerMessage, WorkflowStatusMessage, WorkflowListMessage, WorkflowCancelMessage,
  HealthCheckMessage, HealthStatusMessage,
  QueryActivityMessage, SearchCodeMessage, ReplaySessionMessage,
  LinkTaskMessage, GetTaskLinksMessage, GetReviewBundleMessage, GenerateReviewBundleMessage,
  GetAnalyticsMessage, RetroStartSessionMessage, RetroSubmitReviewMessage,
  RetroSubmitSynthesisMessage, RetroStatusMessage, RetroGetPastLearningsMessage,
  SubscribeMessage, UnsubscribeMessage,
} from "./message-schemas-ext";

export const DaemonMessageSchema = z.discriminatedUnion("type", [
  AuthMessage,
  PingMessage,
  ConfigReloadMessage,
  SendMessageMsg,
  CountUnreadMessage,
  ReadMessagesMessage,
  ListAccountsMessage,
  ArchiveMessagesMessage,
  HandoffTaskMessage,
  ReauthorizeDelegationMessage,
  HandoffAcceptMessage,
  SuggestAssigneeMessage,
  UpdateTaskStatusMessage,
  ReportProgressMessage,
  AdaptiveSlaCheckMessage,
  GetTrustMessage,
  ReinstateAgentMessage,
  CheckCircuitBreakerMessage,
  PrepareWorktreeMessage,
  GetWorkspaceStatusMessage,
  CleanupWorkspaceMessage,
  CouncilAnalyzeMessage,
  CouncilVerifyMessage,
  CouncilDiscussionMessage,
  CouncilHistoryMessage,
  SearchKnowledgeMessage,
  IndexNoteMessage,
  ShareSessionMessage,
  JoinSessionMessage,
  SessionBroadcastMessage,
  SessionStatusMessage,
  SessionHistoryMessage,
  LeaveSessionMessage,
  SessionPingMessage,
  NameSessionMessage,
  ListSessionsMessage,
  SearchSessionsMessage,
  WorkflowTriggerMessage,
  WorkflowStatusMessage,
  WorkflowListMessage,
  WorkflowCancelMessage,
  HealthCheckMessage,
  HealthStatusMessage,
  QueryActivityMessage,
  SearchCodeMessage,
  ReplaySessionMessage,
  LinkTaskMessage,
  GetTaskLinksMessage,
  GetReviewBundleMessage,
  GenerateReviewBundleMessage,
  GetAnalyticsMessage,
  RetroStartSessionMessage,
  RetroSubmitReviewMessage,
  RetroSubmitSynthesisMessage,
  RetroStatusMessage,
  RetroGetPastLearningsMessage,
  SubscribeMessage,
  UnsubscribeMessage,
]);

export type DaemonMessage = z.infer<typeof DaemonMessageSchema>;

export {
  AccountNameSchema,
  HexColorSchema,
  ProviderSchema,
  AddAccountArgsSchema,
  ConfigSetArgsSchema,
  SessionNameArgsSchema,
  LaunchDirSchema,
  SearchPatternSchema,
} from "./cli-schemas";
